### ISSUE TITLE
Поле pg testing mode должно иметь значение логического типа.

### ISSUE THREAD

**Issue by muxammed** [PayBox/SDK_iOS-input-#1]
Здравствуйте
попробовал пользоваться которое то время работало а теперь стало возвращать данную ошибку 
"Поле pg testing mode должно иметь значение логического типа."
не могли бы подсказать вчем проблема?

                        let builder = PBHelper.Builder(secretKey: "LjvNmjFYuAOrcntJ", merchantId: 502592)
                        builder.paymentSystem(system: .EPAYWEBKZT)
                        builder.paymentCurrency(currency: .KZT)
                        builder.autoClearing(enabled: true)
                        builder.enableRecurring(lifetime: 3)
                        builder.paymentLifeTime(lifetime: 300)
                        builder.pbDelegate(delegate:self)
                        builder.testMode(enabled: true)
                        builder.build()

**Comment by mergen88** [comment]
Здравствуйте! Проблема исправлена.
