### ISSUE TITLE
Trouble with payment method 

### ISSUE THREAD

**Issue by zariAlim** [PayBox/SDK_iOS-input-#6]
Добрый день! Оплата не проходит с картами 3D secure после заполнение данных карт  выдает ошибку "Код ошибки 7008". При этом карты без secure проходят успешно. 
![Simulator Screen Shot - iPhone XR - 2020-04-06 at 21 32 31](https://user-images.githubusercontent.com/42088478/78760115-7ef6fc80-79a2-11ea-81f8-7e203a022f9b.png)

**Comment by Gibrat-Erisov** [comment]
Как вы решили проблему ?
